### ISSUE TITLE
Bug in pinyin tone conversion

### ISSUE THREAD

**Issue by anhtuan23** [matthin/cedict_to_sqlite#4]
Sorry to bother you again but there is another unaccounted case of that pinyin conversion script, which is the `ü` sound. For example, when search for `绿`, the output is `lu:4` instead of `lǜ`. 

Looking forward for you to have this bug bashed :)

**Comment by matthin** [comment]
It's not a bother at all, don't worry. It's good that you're letting me know about these bugs.

Converting numbered tones to accent tones seems to be quite a bit more complicated than I first thought. I think I'm probably going to completely rewrite that part of the code as a separate library.

But one thing is that at the beginning of July I'm travelling for 2 weeks and I think my laptop charger is broken, so I probably won't be fixing any more bugs after this one until I'm back. But if you find and fix any more bugs while I'm gone I'll accept them in mid-July when I get back.

**Comment by matthin** [comment]
481a26b061e31fe3decf1ce36ce8ec3488d52871 fixes that issue. The fix is pretty bad code, but since I'm going to completely rewrite it next month I think it's fine for now.

Is it normal for the pinyin for those characters to have a : in there? It seems weird to me.

**Comment by anhtuan23** [comment]
The `u:` stands for `ü` vowel. If you type on keyboard, you would use the `v` key to make that symbol. It's a normal Chinese vowel but does not exist in English. Hence they use that weird symbol to represent it.

There are quite few sound that has this vowel though, only `nü`, `lü`, `nüe`, and `lüe`. Your fix is missing on the `üe` sound by the way. So I will make your code worse with a pull request to fix that.

And 上路平安.

**Comment by matthin** [comment]
I have heard about using v when typing chinese on a normal keyboard, but for whatever reason just haven't seen u: used before. I just expected v to also be used when displaying that vowel in pinyin, but I guess u: does probably make more sense.

It's funny how I could sort of understand that from the limited Japanese I know. I read that as above something (couldn't remember that was road) peace.
